# Generated by Django 5.1.2 on 2025-03-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("Income", "income"), ("expense", "Expense")], max_length=7
            ),
        ),
    ]
